-- ============================================
-- SCHEMA FOR MediHealth appointments table
-- This file describes the structure of the table
-- used by the MediHealth Appointments project.
-- ============================================

--- Code to create table

CREATE TABLE appointments (
  appointment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name text NOT NULL,
  patient_email text NOT NULL,
  patient_age smallint NOT NULL,
  patient_number text NOT NULL,
  appointment_at date NOT NULL,
  reason_for_visit text
);

-- Code to insert rows to table

INSERT INTO appointments (
    patient_name,
    patient_email,
    patient_age,
    patient_number,
    appointment_at,
    reason_for_visit
) VALUES
('Alice Brown', 'alice.brown@example.com', 42, '+447900111222', '2025-12-10 09:00:00', 'Dental cleaning'),
('Bob White', 'bob.white@example.com', 50, '+447900333444', '2025-12-10 10:30:00', 'Eye check-up'),
('Charlie Green', 'charlie.green@example.com', 29, '+447900555666', '2025-12-11 14:00:00', 'Routine physical'),
('Diana Black', 'diana.black@example.com', 36, '+447900777888', '2025-12-12 11:15:00', 'Blood test'),
('Edward Gray', 'edward.gray@example.com', 61, '+447900999000', '2025-12-13 15:45:00', 'Follow-up consultation'); 